### ISSUE TITLE
Feature request: Add back-to-top button

### ISSUE THREAD

**Issue by taka-0770** [SignalFlagZ/sd-civitai-browser#10]
If possible, could you add a way to easily return to the top after going to the bottom of the screen in Civitai Browser?

**Comment by SignalFlagZ** [comment]
That's a good feature. I wanted it when it was a model with a long explanation. I'm thinking of including a review of the UI design. I still haven't come up with a good design.

**Comment by SignalFlagZ** [comment]
Added 37ec597b779978cbc055b882516be8890f7888b1

**Comment by SignalFlagZ** [comment]
Sticky doesn't work with sd.next. Because the parent element has overflow:hidden. What should I do?

**Comment by taka-0770** [comment]
Press the TOP mark to open a new window and return to the main screen. I would like to be able to move to the top of the page if possible.

**Comment by SignalFlagZ** [comment]
What browser?

**Comment by taka-0770** [comment]
It's a browser called brave. When you click it, you will see http://127.0.0.1:7860/#civsfz_apicontrol0

**Comment by SignalFlagZ** [comment]
Please check your browser settings.
Minor browsers cannot be supported.

**Comment by SignalFlagZ** [comment]
FYI. https://github.com/gradio-app/gradio/issues/3667
Depending on the version of gradio, it may open in a new tab.
Markdown components have the same problem.

**Comment by SignalFlagZ** [comment]
Changed back-to-top to javascript instead of a tag for compatibility. 3634366eb8fe5082b3f9701a0dfb46d093789000
The code is not maintainable so I may revert it in the future.

**Comment by taka-0770** [comment]
thx, I was able to fly upwards with Brave safely.
