### ISSUE TITLE
【bug】Model name drop-down cannot be selected

### ISSUE THREAD

**Issue by taka-0770** [SignalFlagZ/sd-civitai-browser#12]
Has the design changed to a model name drop-down that cannot be selected?
It is marked with a round diagonal line and cannot be selected
![WS00000116](https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/145536910/91e909e0-3051-4465-b241-4f54545117c1)

**Comment by SignalFlagZ** [comment]
Model card clicks are now always enabled, so the model drop-down list is no longer interactive. This reduces model display time.
