### ISSUE TITLE
Request for additional functionality

### ISSUE THREAD

**Issue by teketekeFor** [SignalFlagZ/sd-civitai-browser#13]
Is it possible to make the display of whether a file has been downloaded or not trackable when the 'Save folder' is changed? There are instances where it's difficult to determine if the color-changing feature indicating whether a file has been downloaded or not is responsive when the 'Save folder' is altered. If possible, it would be helpful to have a tracking mechanism in place for such cases

**Comment by SignalFlagZ** [comment]
To achieve this, we must record  folders where the models are saved. In most cases, this results in decreased performance. You probably already know that model scanning times are long. What happens if many other extensions do the same thing?
This extension focuses on browsing functionality.
