### ISSUE TITLE
Unable to search using the search function

### ISSUE THREAD

**Issue by teketekeFor** [SignalFlagZ/sd-civitai-browser#14]
It seems that the search function is not working properly. When I use the search on the ChilloutMix site, it displays correctly, but even when I search by model name using the extension, it doesn't show up. There are also some models that don't appear even when searching with the model name displayed on the site or in the extension. Is this a bug, or is it part of the site's design?

**Comment by SignalFlagZ** [comment]
The default search period is now `Month`. Probably for this reason.

**Comment by teketekeFor** [comment]
thx
