### ISSUE TITLE
Downloaded models not showing in browser

### ISSUE THREAD

**Issue by Deckdragon** [SignalFlagZ/sd-civitai-browser#15]
Downloaded files don't show in the browser

**Comment by SignalFlagZ** [comment]
If you don't scan, you won't see new files.

**Comment by Deckdragon** [comment]
When i use the browser it doesn't show any that i already have downloaded

**Comment by SignalFlagZ** [comment]
I don't understand your situation. What is the browser? What did you do?  what do you expect to happen?
If you change the save folder and download it, it will not be displayed. If there are multiple files, only the first file is checked. Have you downloaded the second file or more?

**Comment by SignalFlagZ** [comment]
Closed as there is no additional information
