### ISSUE TITLE
Slash "/" in model names generates subfolders when downloading the model.

### ISSUE THREAD

**Issue by loban4** [SignalFlagZ/sd-civitai-browser#16]
When downloading a model with a"/" in the title additional subfolders will be generated for the each "/".
Example: https://civitai.com/models/125703
Will lead to a path like this: 
"C:\StableDiffusion\SD WebUI\models\Stable-diffusion\_SDXL_1_0\ProtoVision_XL_-_High_Fidelity_3D_\_Photorealism_\_Anime_\_hyperrealism_-_No_Refiner_Needed"

**Comment by SignalFlagZ** [comment]
I was considering how to handle "/". Currently, it is treated as a subfolder.
I know that English-style address formats don't work well.

**Comment by SignalFlagZ** [comment]
Close. There seems to be no opinion.
