### ISSUE TITLE
browser1のタブだとダウンロードできない、かもしれない？

### ISSUE THREAD

**Issue by hilofumi** [SignalFlagZ/sd-civitai-browser#17]
数日前からbrowser1のタブでダウンロードしようとすると、進捗の項目が、0MB/0MBになってしまって直後にERRORの表示が出てきます。
昨日、10/31までは一部のmodelだけだったのが、11/1は試したすべてのmodelが上記のようになってしまいます。

試しにbrowser3のタブを使ってみたらあっさりダウンロードできました。

**Comment by hilofumi** [comment]
あ、やっぱりダメでした。browser2でも3でも出来ませんでした。

**Comment by SignalFlagZ** [comment]
報告ありがとうございます。
CivitaiのAPIサーバーは時々不安定、あるいはメンテナンス状態になるようです。Civitaiホームページに問題なくとも APIサーバーの応答が悪い事は頻繁にあります。
新しいモデルはアップロード者がまだアップロードしていない、ファイルを入れ替え中、アップロード途中などの状態でもモデル情報を送ってくるようです。半日くらい様子を見ましょう。
ここ数日、私が使っていた時には大きな問題はありませんでした。
ちなみに タブ間で動作に違いはありません。

**Comment by hilofumi** [comment]
なるほどですね、了解しました。
ありがとうございます。

ホームページは見られるのになーって思って思わず書き込んでしまいました。
お手数をおかけいたしました。

いつもYouTube見て応援しています。

**Comment by SignalFlagZ** [comment]
クローズします
