### ISSUE TITLE
【request】I would like to request the addition of Aria2's features for downloads

### ISSUE THREAD

**Issue by teketekeFor** [SignalFlagZ/sd-civitai-browser#18]
include the lightweight functionality of Aria2

**Comment by teketekeFor** [comment]
I often find that downloads are finished in the command line but they still appear to be ongoing in the browser

**Comment by SignalFlagZ** [comment]
Thanks for the suggestion.
I don't think using aria2 is a good idea. That will increase the load on Civitai server. The result will not be good for us.
