### ISSUE TITLE
[Improvement Request] Measures for "Model not found" Issue

### ISSUE THREAD

**Issue by teketekeFor** [SignalFlagZ/sd-civitai-browser#19]
I can't say for certain at the moment, but similar to the LORA at https://civitai.com/models/190437, when you click on "Download here" displayed on the civitai browser page, it results in a "Model not found" error. However, if you go to the civitai's LORA page, you can download it using the download button. Is it possible to rectify this issue?

**Comment by SignalFlagZ** [comment]
Thank you for the report!
I know there are such problems. Please check the file ID of the download URL. The file IDs will be different like 213855 and 213856. These are different files. Returns different files on homepage and API.
This seems to be an issue on Civitai's side. I can't do anything about it. If you find a erroneous model, please report it on Civitai's Discord, etc. and it may be fixed.
A similar issue occurs with file hash values.

**Comment by teketekeFor** [comment]
Understood. If possible, can you make it so that when 'Download here' is clicked on the Civitai browser, the screen does not switch if 'Model not found' occurs?

**Comment by SignalFlagZ** [comment]
Making that change will result in wasted traffic of checking for the existence of the file every time you display the model. So I won't make that change.
I was a little surprised as I didn't expect the download link to be used.

**Comment by teketekeFor** [comment]
Recently, the response from civitai has been poor, with frequent errors in the command line. As a result, it's faster to use the civitai browser to copy folders and directly click on download links to download them. I'm reluctantly using links, but it's quicker than opening the website

**Comment by teketekeFor** [comment]
I'm sorry to ask for more, but no matter how many times I press cancel, it won't cancel in the command line. Is there anything that can be done about this?

**Comment by SignalFlagZ** [comment]
Thank you. However, that is a different issue, so please open a new issue. Please write any error messages.

**Comment by teketekeFor** [comment]
Sorry for the inconvenience. Could you please make it so that when I click on 'Download Here', it opens in a new page? It would be helpful if it behaved like when I click on a model's URL, opening in a new page
