### ISSUE TITLE
【bug?】Trying to download the wrong version of the model

### ISSUE THREAD

**Issue by teketekeFor** [SignalFlagZ/sd-civitai-browser#20]
There seems to be a bug where downloading a different version than the one displayed occurs. For instance, when attempting to download model data like Cynthia R0, Cynthia K9, Cynthia H7, Cynthia D5, Cynthia C3 on the Civitai browser, it appears to aim for the 1109 model. However, what actually gets downloaded results in an error, leading to the phenomenon where the 1108 version is downloaded instead on the website

can be translated to native English as
I tested it, but it's showing as 1108 normally.Please check if the access route is the URL below.
https://civitai.com/models/192555?modelVersionId=219206
1109 version has been booked,It seems to have been connected to the 1109 version address due to a system error.
The current released version is 1108.

after
Cynthia R0
Civitai link (if exist): https://civitai.com/models/192555
The civitai browser lists it as version 1111, but the download URL and others are for version 1108

**Comment by SignalFlagZ** [comment]
Can you log in to Civitai and download correctly? 
CivBrowser does not have the feature to send API key.

**Comment by teketekeFor** [comment]
I'm using it locally, and there's a discrepancy between what is displayed in the Civitai browser and the URL being shown in the Civitai browser

**Comment by SignalFlagZ** [comment]
This is not a bug. You have found the correct model's website from the link.  There is only one link to the model.
You wrote "has been booked" yourself. There's versions that hasn't been released yet. Downloading it will fail.
