### ISSUE TITLE
[Request] Display safetensor file first when there are multiple files

### ISSUE THREAD

**Issue by teketekeFor** [SignalFlagZ/sd-civitai-browser#22]
While browsing with the civitai browser, I noticed that files like 226804_training_data.zip are prominently displayed, similar to the URL https://civitai.com/models/201512. However, when clicking on the site's download link, Nuwa_Nightstone__Character_LoRA.safetensors is downloaded instead. The zip file does not seem to exist on the site. This issue occurs with zip, safetensors, pt, and ckpt files. Is there a way to prioritize the display of safetensors, pt, or ckpt files instead of zip in such cases?

**Comment by SignalFlagZ** [comment]
Thank you for the report.
Although it is a low priority, I would like to improve it in the future.

**Comment by SignalFlagZ** [comment]
Implemented. 9247a50646072113efbd06738b443d1f81023328
