### ISSUE TITLE
【Question】Why are there different errors for seemingly similar ?

### ISSUE THREAD

**Issue by teketekeFor** [SignalFlagZ/sd-civitai-browser#24]
Even if the download is successful, sometimes there's a message saying the hash value is different. How is this different from the error stating that the download can't proceed due to a different hash value, as shown in the 0MB/0MB error?

**Comment by SignalFlagZ** [comment]
I don't understand the meaning of the question.  What does a successful download mean? If the hash value is different, it is not a success.
