### ISSUE TITLE
「バグ報告」civitai ブラウザー上でモデルファイル名が「%E3%83%AD%E3」等になっていた場合とサイトのURLの番号テキストだけの場合があり

### ISSUE THREAD

**Issue by beatrun2006** [SignalFlagZ/sd-civitai-browser#26]
今回、検証したのはhttps://civitai.com/models/209203 のLORAモデルです。（他にもあったりするのですが直近で出た物なので）

表示されるカード:正常
モデル名:正常
バージョン:正常
ターゲットタグ:なし
セーブフォルダー:正常
モデルファイル名:zipは正常、safetensorsが%E3%83%AD%E3%8　省略　%83%88Laurecia_Le_Blanchette-000008.safetensors表記

save traineed tagsで%E3%83%AD%E3%83%BC%E3%83　省略　3%83%88Laurecia_Le_Blanchette-000008
save model infoで%E3%83%AD%E3%83%BC%E3%83%　省略　3%83%88Laurecia_Le_Blanchette-000008_0.pngから＿3.png
download modelで%E3%83%AD%E3%83%BC%E3　省略　83%E3%83%88Laurecia_Le_Blanchette-000008.safetensors
ダウンロード完了時にCivBrowser: No hash value provided. Unable to confirm file表示

フォルダの中を見ると上記の表示名のものばかりでSD起動時にはsafetensorsじゃないぞって怒られるパターンです。
サイトに移動して落として来ましたが正常なファイル名でした。

個人的に対策としては手動でモデルだけサイトに移動して落として来て正常なファイル名を他のファイルに付け直しましたが
割と文字化けファイルがあったりするので対策があれば改善お願いします。

もう１つのバグが
download modelで何故かサイトのURLの番号テキストだけの場合があります。
こちらは検証しようと思ったのですがテキストだけになってるフォルダを探し出すのが面倒だったのと
数字だけのモデル名があったりするので時間かかりそうだった為、やってません。

**Comment by SignalFlagZ** [comment]
報告ありがとうございます。
文字化けするモデルがあるとは気づいていました。Civitaiから送られてくるデータ自体がそうなっています。
[https://civitai.com/api/v1/models?types=LORA&sort=Newest&query=Laurecia](https://civitai.com/api/v1/models?types=LORA&sort=Newest&query=Laurecia)
ファイル名がURLエンコードされています。デコードするにはエンコードに使った文字コードを知っていなくてはなりません。しかしその情報はどこにもありません。たぶん文字コードはUTF-8なのでデコードする事は可能です。ですがすべてのファイル名がURLエンコードされているわけでもなく、無条件にデコードするとかえって間違った文字にしてしまうかもしれません。今回のモデルではzipの方はURLエンコードされていません。
そもそも論としてURLエンコードされたままのファイル名がなぜあるのか？とか どこで誰が対応すべきかはっきりしません。
一番の対策はアップロード者へ連絡してファイル名を変えてもらうことでしょう。

>download modelで何故かサイトのURLの番号テキストだけの場合があります。

どんな症状がわかりません。番号のテキストだけとは何でしょうか？ しばらく気にしながら見てみます。
モデル情報は毎回正しいものが送られてくる訳ではありません。Civitaiサーバーはとても不安定なようでちょくちょく間違ったデータをしれっと送ってきます。そんな時はモデルカードをもう一度クリックしデータを読み込みし直してください。ダウンロード後Hash値が違うと言われたときもモデルを読み込み直すとダウンロードできたりします。

**Comment by beatrun2006** [comment]
了解しました

**Comment by SignalFlagZ** [comment]
6d864ed5af50da211a87c7ecc3abf73ff36b2a45 
ファイル名をすべてデコードするよう更新しました
