### ISSUE TITLE
No CivBrowser tab

### ISSUE THREAD

**Issue by juliux32** [SignalFlagZ/sd-civitai-browser#27]
Here's a video and as you can see, there's no tab

https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/21074960/0ccae803-e157-48c7-836e-e54f3de3d427

**Comment by SignalFlagZ** [comment]
Thank you for your report.
Please check the console message when starting the SD web UI. Are any errors displayed?

**Comment by juliux32** [comment]
Here it is 

![2024-01-30 13-30-25](https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/21074960/5f8eabab-25ae-4f83-86b4-661981e1cde6)

**Comment by juliux32** [comment]
@SignalFlagZ Here it is 

![2024-01-30 13-30-25](https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/21074960/7a5a7e39-f249-4e06-bba2-4b046312b695)

**Comment by SignalFlagZ** [comment]
It seems that `colorama` is not installed as stated in the message. `colorama` is installed when SD web UI starts. There seems to be a `colorama` installation failure message before this message. To manually install `colorama`, do `pip install colorama` in your python venv.
However, I don't understand why `colorama` installation fails. What OS and python version are you using?

**Comment by juliux32** [comment]
@SignalFlagZ I'm running in on Runpod

**Comment by SignalFlagZ** [comment]
Due to the special environment, I cannot respond. Please ask RunPod management how to install the package.
If there is a way to identify that it is running on RunPod, please let me know.

**Comment by juliux32** [comment]
@SignalFlagZ RunPod responded that they can't help, because it is not their application/code/extension and I should contact to those who have created this and have all the information about their code

**Comment by SignalFlagZ** [comment]
> @SignalFlagZ RunPod responded that they can't help, because it is not their application/code/extension and I should contact to those who have created this and have all the information about their code

You shouldn't have asked them that some program didn't work. If you can install the colorama package, the Extension will work.  It's a common package in python. How to install a package is an OS issue or service specification. It's not a program code problem. So I can't do anything from my code running on the OS.
However, I have the option of not using the colorama package. Without knowing why Runpod can't install the colorama package, I won't make that choice. Debugging on an unknown OS is impossible.

**Comment by juliux32** [comment]
@SignalFlagZ Using their terminal in Jupyter, I managed to install it by using your provided comand **pip install colorama** in python venv and now I can see your extension. Thank You for your assistance

**Comment by SignalFlagZ** [comment]
> @SignalFlagZ Using their terminal in Jupyter, I managed to install it by using your provided comand **pip install colorama** in python venv and now I can see your extension. Thank You for your assistance

Congratulations, you'll probably face similar problems in the future, but you now have the skills to solve them yourself.
Close issue.
