### ISSUE TITLE
タイプ別保存サブフォルダーの指定について

### ISSUE THREAD

**Issue by taka0070** [SignalFlagZ/sd-civitai-browser#29]
civsfz_filemanage.pyの　
![WS000030](https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/129574158/8ec5b1e9-f966-4c91-8bcb-bf28886568b0)
にあるLoConの項目をmodels/Loraに書き換えたのですが
civbrowserの方ではmodels\LyCORIS\の表記のまま変更されません、

前回変更して反映もされていたのですがここ最近webUIの拡張のアップデート確認で２回アプデされていた模様ですが
それ以降変更の反映がされない状態です。

また、civbrowserのアップデートが行われた場合、
![WS000031](https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/129574158/113ffbe9-fe7c-46ff-a70e-50557bea88b4)
と元通りになってしまいます。

この項目をcivbrowserの設定で選べるようにして頂けると助かります。

**Comment by SignalFlagZ** [comment]
コードを直接変更したのなら すべてあなたの責任です 自分で解決しましょう
返答することは何もありません
