### ISSUE TITLE
KeyError:’meta' バグ：モデルカードを選択するとエラー表示

### ISSUE THREAD

**Issue by Taskmak** [SignalFlagZ/sd-civitai-browser#31]
検索は出来ますが
モデルcardを選択するとエラーが表示され以下の表示がコマンドラインに出ます。
![WS000036](https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/161118354/c2b8e485-c98f-496b-992d-9f88f94f68a8)

**Comment by SignalFlagZ** [comment]
CivitaiのAPI レスポンスから meta キーが消えていますサンプル画像のinfotextが記録されているキーです。
エラー回避の修正をしました b5a5c44020f5c3e38507f540fc8052c588bcf03e
Updateしてください。
"Save model infos" でもinfotextは欠落しているので注意してください
metaキーが復活すれば今までと同じになります

**Comment by SignalFlagZ** [comment]
f405625f95b1b164e9f07c40039d878c47b45be0
Get meta key from images API. This is an experimental procedure.
The infotext can be displayed.

**Comment by SignalFlagZ** [comment]
Hide the infotext because it was displaying infotext different from the image 095b4107d71f71e4679a241b8506d88d207f7a50
I can't find a good way to get meta information. Version ID doesn't work well. Am I misunderstanding something?

**Comment by SignalFlagZ** [comment]
f234bbe2e1e1d49a1bec33112e365fa8b33cfd17 Check image and infotext match using image ID.  v1.12.2
