### ISSUE TITLE
ダウンロード出来ているのにカードの色が変わらないものが存在する

### ISSUE THREAD

**Issue by Taskmak** [SignalFlagZ/sd-civitai-browser#32]
ダウンロードが済み、所定のフォルダに帆zンされて存在するにも関わらずカードの色が変わらないことがある

https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/161118354/9553f149-80cc-4229-b6bb-50174c4b0ecf

この様な感じです。ほかにもダウンロードが終了しているにも拘らず色が変わらないものが割と多いです。

**Comment by SignalFlagZ** [comment]
報告ありがとうございます。
その症状は時々見かけ気づいていました。モデルファイルを消して再ダウンロードすると正しく表示したりします。絶妙に再現性が乏しくデバッグできていません。確実に再現するモデルIDがあれば何か考えられそうなのですが、今のところ原因を特定できていません。

**Comment by Taskmak** [comment]
現状、https://civitai.com/models/267925
のLoconが該当しますね

**Comment by SignalFlagZ** [comment]
情報ありがとう
不具合の再現ができました。原因もわかりました。
モデル情報に`v1.0`が2つ存在します。カード部とダウンロード部で異なる`v1.0`を認識しています。そのためダウンロードしてもカード部はファイルが無いと表示します。カード部は一番始めにある`v1.0`で動き、ダウンロード部は一番最後の`v1.0`で上書きしてしまいます。
バージョン名が重複しないようモデルアップロード者様に修正をお願いするのが一番良い解決方法になります。
この問題が生じる可能性は以前から認識していました。修正が少し複雑で手をつけていませんでした。修正を試みますがかなり時間がかかるかもしれません。それまではCivitaiでのダウンロードをお願いします。

**Comment by SignalFlagZ** [comment]
思っていたより簡単に修正できました。v1.13.1とします。
