### ISSUE TITLE
特定Loraのパーミッションが異なって表示される2

### ISSUE THREAD

**Issue by CircleD5** [SignalFlagZ/sd-civitai-browser#33]
**Describe the bug**
特定Loraのパーミッションが異なって表示されるという現象に遭遇しました。

以下が異なるパーミッションが表示されるLoraです。
https://civitai.com/models/229213/extremely-detailed-sliders-ntcaixyz?modelVersionId=258687

![スクリーンショット 2024-03-01 080726](https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/144087288/0e2d235b-d0da-45e2-97dc-c689dd9acb27)

**To Reproduce**
上記のLoraをCivBrowserで表示されると再現できます。

**Expected behavior**
上記のLoraの場合、モデル登録者が制限を課していない場合、
あらゆる利用が可能となるはずなので、すべての項目が✅になるはずです。

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - UI and Version: Webui Forge 1.8.0rc
 - CivBrowser Version:  b9bdbca7 | 2024-02-28 21:19:57

**Comment by CircleD5** [comment]
追記：　どうやら他のモデルでも起きている様子。
　いまいち規則性がわからず、わかったら追記します。

**Comment by CircleD5** [comment]
あ、調査してみたところ、item['allowCommercialUse']がこれまでEnumだったのがリストになってるっぽい？（ ['Image', 'RentCivit', 'Rent']みたいな感じで、権限のリストになっていた）
公式ドキュメントを確認したのですが、そちらはまだ、Enumって書いてあるので、また、こっそりCivitaiがAPIの仕様を変えたのかもしれません。

**Comment by SignalFlagZ** [comment]
報告ありがとうございます 調査までしていただき感謝です
少し調査して対応を考えます 一時的にPermissionsはCivitaiページへのリンク表示にするかもしれません
最近APIのレスポンスで見たこと無いなぁ というのが増えています マネタイズを模索している感じでしょうか リストになったという事は今後も増えて複雑化するかもしれませんね

**Comment by SignalFlagZ** [comment]
修正しました 3baa977133436c3d3e87eb60057bc976596d3b91
しばらくパーミッションの確認をお願いします

**Comment by CircleD5** [comment]
早速のご対応、ありがとうございます！
先ほど、正しくパーミッションが表示されることを確認いたしました！！
