### ISSUE TITLE
Civitai's API response has changed significantly, which will cause many errors （KeyError: 'currentPage' occurs）

### ISSUE THREAD

**Issue by SignalFlagZ** [SignalFlagZ/sd-civitai-browser#37]
CivBrowser v1.16.1

Can't get card list.
```
  File "D:\StableDiffusion\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-civbrowser\scripts\civsfz_api.py", line 427, in getCurrentPage
    return f"{self.jsonData['metadata']['currentPage']}"
KeyError: 'currentPage'
```

**Comment by SignalFlagZ** [comment]
It seems that the specifications of API response metadata have changed.

**Comment by SignalFlagZ** [comment]
createdAt  and updatedAt disappeared

**Comment by SignalFlagZ** [comment]
How to use cursor? The meaning is unclear and pagination is not possible.
The next page is shown, but I can't go back or jump.

**Comment by SignalFlagZ** [comment]
The cursor seems to be related to the model's publish date.
Since we don't know the model information, page jumps are impossible.

**Comment by Taskmak** [comment]
ジャンプと戻るは出来なくてもよいので簡易的に現状で公開して頂けると助かります。

**Comment by SignalFlagZ** [comment]
> ジャンプと戻るは出来なくてもよいので簡易的に現状で公開して頂けると助かります。

ちょうど上げました 何が動くのか私もわかっていません

**Comment by Taskmak** [comment]
確認しました。大半がCivBrowser: Error: File download failed.でDL出来ない感じっぽいですね
一応Nextで移動は出来るけどエラーになるんですね💦
簡易的とは言え公開して頂きありがとうございます。
（現状はフォルダをコピって直接ダウンロードで対応しています）

**Comment by SignalFlagZ** [comment]
ダウンロード関係の変更は無いようなのでできるはずです。hash値違いで削除しちゃうのがちらほら。
Nextでエラーが出ても もう一度押すと大丈夫だったりします。
APIのレスポンスがわけわかりません。

**Comment by SignalFlagZ** [comment]
The JSON response structure for query errors has changed.
```
{
    "error": {
        "issues": [ ....
```

**Comment by SignalFlagZ** [comment]
The hash value is now 12 digits. Older models still have 64 digits.
No. It's mixed. Is there a difference in the upload time? But the create time has disappeared, so I can't know.

**Comment by SignalFlagZ** [comment]
It seems that empty keys are no longer included in the response.  The existence of all keys must be confirmed. all? Even though we have no way of knowing what exists? Is it a nightmare?

**Comment by SignalFlagZ** [comment]
Some model has `ValueError: Invalid isoformat string:` '2024-03-16T12:32:03.65' .
There are some models where Zulu, which indicates the time zone, is missing from the publishAt key value.

**Comment by SignalFlagZ** [comment]
> Some model has `ValueError: Invalid isoformat string:` '2024-03-16T12:32:03.65' . There are some models where Zulu, which indicates the time zone, is missing from the publishAt key value.

It seems the database has been updated. Zulu is all gone.

**Comment by SignalFlagZ** [comment]
Even if there are multiple search results pages, the URLs after the second page are unknown.
`nextPage` is missing.

**Comment by SignalFlagZ** [comment]
Support for API changes has been completed.
