### ISSUE TITLE
retry limitの連続

### ISSUE THREAD

**Issue by Taskmak** [SignalFlagZ/sd-civitai-browser#38]
ef2b492f | 2024-03-17 18:05:07　更新のバージョンでモデルやLORAを落とす際にretry limitが連発します

https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/161118354/c571a585-a9e7-43b2-b120-080abf088e3e

**Comment by SignalFlagZ** [comment]
報告ありがとうございます。とても助かります。しばらくは変更箇所が多く動作確認をするパターンが膨れ上がるので見落としが多々あると思います。またAPIの動作がおかしい部分もあります。
APIへのrequest結果をキャッシュするようにしました。キャシュにより高速なページ移動が可能になる かも。
キャッシュが効く範囲を勘違いしていました。APIキーが必要な時にはエラーではなくメッセージページが返ってきます。これをキャッシュしてしまい2回目以降も同じメッセージの処理をしていました。ファイルのダウンロードではキャッシュを無効にするよう変更しました。

**Comment by Taskmak** [comment]
最初だけRetry wait 3sのまま1-2分止まりますね。後は順調にいくみたいです
長いのは5分以上そのままの状態です。

**Comment by SignalFlagZ** [comment]
それは単にCivitaiのサーバーが遅いのでしょう 4Mbyte受信しないと表示が更新されません cancelをして何度かやり直すと速い時があります 最近は夜中に遅くなりますね
