### ISSUE TITLE
Loraをダウンロードする場合に.safetensorsを優先表示して欲しい

### ISSUE THREAD

**Issue by Taskmak** [SignalFlagZ/sd-civitai-browser#39]
サイト上ではzipが存在しませんがAPI上ではzipと.safetensorsの２種類表示される場合があります。
その場合は.safetensorsを優先表示する様にして欲しいです。

**Comment by SignalFlagZ** [comment]
Duplicate of #22
zipでエラーが出るのでなおさらそう思いますよね。なんでzipが存在しているのでしょうね。アップロード者だけが見れるのでしょうか？それなら表示せず消しても良いのだろうか？
というように、これ意外と難しいのです。workflowなどはzipなのでやっつけな並び替えはできません。APIのレスポンスだけから優先順位を決めなくてはなりません。どんなファイルが添付されるかわからない状況で何を根拠に並び替えるのか？ プログラム的にどこで並び替えるのが良いか？将来的に追加・変更は簡単か？など ドキュメントが無いのでAPIの設計意図を推測しなくてはなりません。まぁそれっぽいキーはあるのでそろそろやろうとは思っています。

**Comment by SignalFlagZ** [comment]
漠然と考えていたのを実装しました 9247a50646072113efbd06738b443d1f81023328
長々言い訳を書いていたけど5分で終わった😅

**Comment by Taskmak** [comment]
問題なく動いてます。ありがとうございます。
