### ISSUE TITLE
Backward incompatibility with Python <3.10

### ISSUE THREAD

**Issue by iafuad** [SignalFlagZ/sd-civitai-browser#4]
The extension uses structural pattern matching [here](https://github.com/SignalFlagZ/sd-civitai-browser/blob/aa109f1f4033b6d63746ffbec25c36d62d12f2ca/scripts/civitai_api.py#L376C11-L376C11) and [here](https://github.com/SignalFlagZ/sd-civitai-browser/blob/aa109f1f4033b6d63746ffbec25c36d62d12f2ca/scripts/civitai_api.py#L390) which was introduced in Python 3.10. Which makes this great extension incompatible with Python versions <3.10. It would be great if you convert them to simple `if else` statements.

**Comment by SignalFlagZ** [comment]
Thank you for your feedback!  I was a little worried about it.
Will you use this extension in Python <3.10 ?  Stable Diffusion web UI requires 3.10.6 or high.

**Comment by iafuad** [comment]
> Thank you for your feedback! I was a little worried about it. Will you use this extension in Python <3.10 ? Stable Diffusion web UI requires 3.10.6 or high.

Thank you for your reply. Yes, the **suggested** version of Python with WebUI is 3.10. But it is still compatible with 3.8 and 3.9. Also, recently i've seen a commit that further confirms that WebUI still supports Python <3.10 ([f82e08c](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/f82e08cf45e9eb0ea4fa15825f27313b8e78a73c)). So I think it is only natural that extensions also support versions <3.10.

**Comment by SignalFlagZ** [comment]
de25403ea70effc68d0c38518eb4a2241b925e3d
I don't have Python <3.10 environment, so I only test with 3.10.
