### ISSUE TITLE
APIのnsfw仕様変更に伴う KeyError: 'nsfw'

### ISSUE THREAD

**Issue by Taskmak** [SignalFlagZ/sd-civitai-browser#40]
昨晩は問題なく利用できたのですが今朝からKeyError: 'nsfw'でエラーを連発しています

New Content Rating System
We've updated our content rating system to both enhance and simplify the content browsing experience. Going forward, Civitai will rate content into five easy to understand rating levels, much like those used in movie/film rating classifications. Please read our [Guide to Content Classification](https://education.civitai.com/civitais-guide-to-content-levels) for more information!

って事になってる用でNSFWだけではなくコンテンツが分かれたのが原因の様です

**Comment by SignalFlagZ** [comment]
報告ありがとうございます。関連リンクまで調べていただき感謝です。
こんなディスカッションがされていたのは知っていましたが実施されてしまったようですね。問題は具体的にAPIの中身がどう変わったかなのですが、たぶんドキュメント化されていないのでしらみつぶしにレスポンスの中身を見ないとならないようです。
今日の昼間は時間がとれないので対応に少し時間がかかるかもしれません。

**Comment by SignalFlagZ** [comment]
`nsfwLevel`というキーが追加されている。値は数値。1、9、28、4，2、7、8などがある。何を意味しているか不明。フラグとは思えない数値。年齢でもないだろう。
一時的なエラー回避は可能だがnsfwなものをそのまま表示する修正はしたくない。情報収集を続ける。

**Comment by SignalFlagZ** [comment]
仮にnsfwエラーを回避したら`KeyError: 'meta'`が出る。以前にmeta情報が削除されたのでModel Version APIからmeta情報を拾ってくるようにしたのだが、今回 Models APIとModel Version APIとでサンプル画像の数が合わなくなっている。そのためmetaキーが無いモデル情報が出来上がりエラーとなる。画像とmeta情報が一致しているかの判断も怪しくなる。レスポンスにimage IDが無いので確かめる術がない。
API変更の着地点が予測できないので対処方法に迷う。

**Comment by SignalFlagZ** [comment]
`PG`っぽい値は`1`のようだ。これで一時的に動くようにしてみる。
`nsfwLevel`の値はフラグと仮定して `PG` `PG-13` `R` `X` `XXX`のフィルターを作る予定。

**Comment by Taskmak** [comment]
helperを使ってみましたが画像に関しての数値っぽいようですがモデル本体もなのでしょうか？

**Comment by SignalFlagZ** [comment]
> helperを使ってみましたが画像に関しての数値っぽいようですがモデル本体もなのでしょうか？

わかりませんがモデルのレーティングはサンプル画像のフラグの論理和のように見えます。これで出したくない画像を持ったモデルをはじくことができるのでしょう。と仮定しています。

**Comment by SignalFlagZ** [comment]
APIのクエリーに`rating=4`を付けてレスポンスを見てみると16とかのモデルも返ってくる。意味がわからない。効いていないのか？実装がまだなのか？

**Comment by SignalFlagZ** [comment]
`nsfwLevel`は最大で31というつもりでコードを書いていたが33のモデルがある。0は存在しないかと思ったら0もある。何を表しているんだ？

**Comment by SignalFlagZ** [comment]
基本的な対応は完了した b726148da304714e2ce1999bea2977b32c2a330b
