### ISSUE TITLE
ペーストした文字列で検索できない （検索でスペースを挟んでも検索可能にして欲しい）

### ISSUE THREAD

**Issue by Taskmak** [SignalFlagZ/sd-civitai-browser#42]
以前のバージョンではモデルやLORAの検索ではcivitaiのサイトのモデルやLORAのタイトル？そのままをコピペして
検索出来ていましたが最近のバージョンではスペースが挟まると検索出来ないっぽいので改善して欲しいです
例えば https://civitai.com/models/332850 のモデルの場合Real Stable XLの部分をコピペして貼り付けて検索出来ていましたが
今は検索出来ません。また、モデルIDの332850をモデルIDで検索しても表示されません。

検索機能のAPIも変わってるのかもしれませんが対応して頂けると嬉しいです。

**Comment by SignalFlagZ** [comment]
ご意見ありがとう。 この意見はもっと以前に来ると思っていました。
検索履歴を追加した時からペーストした文字列を認識しなくなりました。ペースト直後にエンターキーを押すと文字列を認識します。gradioの仕様との兼ね合いでこうなっています。ペーストだけでは入力として扱われません。キーボードからの入力が必須になっています。
わかりにくいのでどこかに注意を表示したいのですが反応も無いし良い場所がないので放置しています。

**Comment by SignalFlagZ** [comment]
まじめに考えたら簡単に改善できました😅 v1.18.2からはペーストだけで検索できるでしょう。
検索では一つの文字列で検索できます。スペースで2つの単語が有ったとしてもそれは一つの文字列です。2つの単語として扱われる事はありません。
単語を区切る記号があるかもしれないといろいろ試しましたが今のところ見つかりません。
クローズします。
