### ISSUE TITLE
alltimeやnsfwのチェック、PGやXXXの設定の保存

### ISSUE THREAD

**Issue by Taskmak** [SignalFlagZ/sd-civitai-browser#43]
再起動の都度設定し直すのが面倒なので
alltimeやnsfwのチェック、PGやXXXの設定を記憶してくれる機能を付けて頂けると助かります。

**Comment by SignalFlagZ** [comment]
Browsing Levelはすでに設定できるはずです。
検索条件はどうするか検討中です。プログラム的に面白い点が無いのでやる気が出ないし、Settingsの項目は熟考しないとゴミが残るしで方針が決まらないといじりにくいのです。

**Comment by SignalFlagZ** [comment]
検索条件の履歴機能を追加しました。 クローズします。
