### ISSUE TITLE
19βで表示が変わらない

### ISSUE THREAD

**Issue by Taskmak** [SignalFlagZ/sd-civitai-browser#45]
1・今まではダウンロードの進行状況が出ていた画面にQueue 1: Threads 2と表示されるが
ダウンロードが終わったかどうかの確認が出来ない及び表示が変わる様子が無い

2・ダウンロードが終わった場合に今まではinfo表示が出ていたが表示が出なくなった

の２つが発生しています。

**Comment by SignalFlagZ** [comment]
報告ありがとうございます。
端的に言うと仕様です😅
1年前から構想していた別スレッドでのダウンロードなのですが、gradioとの相性が悪くダウンロードの状態を表示することができません。
あまりにも使い勝手が悪いので改善をしているところです。

**Comment by SignalFlagZ** [comment]
c262c6eac59789607208662ee23616a37e8edddf
ダウンロードキューの表示を追加しました。ダウンロードの進捗を表示したいところですが方法が見つかりません。
スレッド化したのでダウンロードの完了を待たず次のダウンロードを始められます。同時ダウンロード数は今のところ2です。それ以上はキューに溜まり先のダウンロードが終わったら順番にダウンロードが開始されます。
補足できないエラーが起きると表示が消えない事があります。そんな時はどんなエラーが起きたか教えて下さい。

**Comment by Taskmak** [comment]
'AsyncRequest' object has no attribute '_json_response_data'
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='9dw8e54iifw_1663' coro=<Queue.process_events() done, defined at C:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py:384> exception=ValueError('[<gradio.queueing.Event object at 0x000001BFEAB35330>] is not in list')>
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py", line 471, in process_events
    self.active_jobs[self.active_jobs.index(events)] = None
ValueError: [<gradio.queueing.Event object at 0x000001BFEAB35330>] is not in list

というエラーが割と出ますね

**Comment by Taskmak** [comment]
1・ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='jlszsuufw1p_1315' coro=<Queue.process_events() done, defined at C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\queueing.py:384> exception=ValueError('[<gradio.queueing.Event object at 0x000001F069DB1C90>] is not in list')>
Traceback (most recent call last):
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\queueing.py", line 471, in process_events
    self.active_jobs[self.active_jobs.index(events)] = None
ValueError: [<gradio.queueing.Event object at 0x000001F069DB1C90>] is not in list
'AsyncRequest' object has no attribute '_json_response_data'
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='jlszsuufw1p_1696' coro=<Queue.process_events() done, defined at C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\queueing.py:384> exception=ValueError('[<gradio.queueing.Event object at 0x000001F069E51F90>] is not in list')>
Traceback (most recent call last):
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\queueing.py", line 471, in process_events
    self.active_jobs[self.active_jobs.index(events)] = None
ValueError: [<gradio.queueing.Event object at 0x000001F069E51F90>] is not in list

というエラーが頻発しています

２・キューに入れてダウンロードに失敗した場合、キューに残ってしまい再起動するまで消えない

**Comment by SignalFlagZ** [comment]
報告ありがとうございます。
どこかで補足していない例外エラーが出ているようですが なんだか全くわかりません。

**Comment by SignalFlagZ** [comment]
ダウンロードの進捗を表示するようにしました 215d7c08d51d46c2f05dc0f933aeb3c6c1811be7

**Comment by Taskmak** [comment]
出来ればリストに表示された項目を削除できる機能を付けて欲しいです。
現状、何かの拍子にファイルが存在しませんと言うエラーが帰ってきた場合に実行リストに残ったままなので
削除できる様にして頂けると助かります

**Comment by SignalFlagZ** [comment]
削除機能は付けません。正常時に削除されると破綻します。
ファイルが存在しない時のエラー処理は追加しました。状況を再現できないので検証できていませんけど。

**Comment by SignalFlagZ** [comment]
> 1・ERROR:asyncio:Task exception was never retrieved future: <Task finished name='jlszsuufw1p_1315' coro=<Queue.process_events() done, defined at C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\queueing.py:384> exception=ValueError('[<gradio.queueing.Event object at 0x000001F069DB1C90>] is not in list')> Traceback (most recent call last): File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\queueing.py", line 471, in process_events self.active_jobs[self.active_jobs.index(events)] = None ValueError: [<gradio.queueing.Event object at 0x000001F069DB1C90>] is not in list 'AsyncRequest' object has no attribute '_json_response_data' ERROR:asyncio:Task exception was never retrieved future: <Task finished name='jlszsuufw1p_1696' coro=<Queue.process_events() done, defined at C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\queueing.py:384> exception=ValueError('[<gradio.queueing.Event object at 0x000001F069E51F90>] is not in list')> Traceback (most recent call last): File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\queueing.py", line 471, in process_events self.active_jobs[self.active_jobs.index(events)] = None ValueError: [<gradio.queueing.Event object at 0x000001F069E51F90>] is not in list
> 
> というエラーが頻発しています

1のエラーはたぶんCivBrowserと関係ありません。ビデオメモリーを使い切った時に出ていませんか？

**Comment by Taskmak** [comment]
SDを起動してbrowserが立ち上がった後にcivitai-browserを起動した直後等に出てました。

別件ですか　Early Accessに対してはエラーでダウンロード出来てないっぽいです。

それと

https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/161118354/d32f86b9-9de2-4ddf-ad08-dc4c249ee82e

この状況になってしまう場合も割と多いです

**Comment by SignalFlagZ** [comment]
>  bandicam.2024-04-22.11-48-40-756.mp4 
> この状況になってしまう場合も割と多いです

Chromium系は最近ずっと動作がおかしいです。Firefoxを使うとよいでしょう。

**Comment by Taskmak** [comment]
Firefoxを使うとよいでしょうとの事だったので使ってみましたが
1回目でこれでしたけどね。不安定なのは不安定っぽいです
https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/161118354/7dbdffd5-9614-42cb-a5af-f78f0b442d60

**Comment by SignalFlagZ** [comment]
> SDを起動してbrowserが立ち上がった後にcivitai-browserを起動した直後等に出てました。

こちらでその症状は出たことがありません。Civitai側の調子も良いようで現在エラーはほぼ出ません。
お使いの環境に関する情報が不明なので何も検討できないです。エラーメッセージからすると特殊なインストールをしているようですね。しばらく様子見してください。

**Comment by Taskmak** [comment]
普通にstable-diffusion-webui-forgeをインストしてるだけですけどね。
18.10では上記のエラーも読み込みの遅延も発生はしません（現在18.10に戻して使用中です）

**Comment by SignalFlagZ** [comment]
> 普通にstable-diffusion-webui-forgeをインストしてるだけですけどね。 18.10では上記のエラーも読み込みの遅延も発生はしません（現在18.10に戻して使用中です）

One-Click Package を使ったのですね。早速ダウンロードして動かしてみました。
```
version: f0.0.17v1.8.0rc-latest-276-g29be1da7 •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: 15012c538f
```
CivBrowserをインストールして何の問題もなく動いています。再インストールを推奨します。
再インストールでダメなら他の拡張機能との干渉があり得ます。組み合わせを一つづつ確認するしかないでしょう。拡張機能にはライブラリ環境を破壊するものもあります。

何を使っているかは最初に書いていただけると助かります。この世には数多くの選択肢があります。Issueは不具合で困った人たちが見に来る場所です。自分と同じ問題かを簡潔に判断するため、動作環境の情報が一番最初に無くてはなりません。

**Comment by Taskmak** [comment]
申しわけなかったです
環境は
![WS000110](https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/161118354/6f5a86bc-7eae-4147-9018-a03a05f782ab)
です

version: f0.0.17v1.8.0rc-latest-276-g29be1da7　 python: 3.10.11 　torch: 2.1.2+cu121　xformers: 0.0.23.post1 　gradio: 3.41.2　checkpoint: 3c33e4d504

**Comment by SignalFlagZ** [comment]
>環境は

検索できるようテキスト推奨です😅

**Comment by Taskmak** [comment]
version: f0.0.17v1.8.0rc-latest-276-g29be1da7　 python: 3.10.11 　torch: 2.1.2+cu121　xformers: 0.0.23.post1 　gradio: 3.41.2　checkpoint: 3c33e4d504

です
