### ISSUE TITLE
Many card images are being set incorrectly

### ISSUE THREAD

**Issue by Succubyss** [SignalFlagZ/sd-civitai-browser#48]
![image](https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/87207237/bf3a0799-c30d-4dc1-b6f9-0d5f5c27a505)

The URLs of the thumbnails correlate to valid paths on my filesystem, however, the broken images turned out to be 0 byte files.

Strangely, every other image associated with these cards downloaded just fine, the only files that have this issue are the card images (i.e. png files without the _0 _1 _2 etc. suffix).

Here's a link to where I got the cards from to help replicate the issue:
<https://civitai.com/models/264290?modelVersionId=396148>

**Comment by SignalFlagZ** [comment]
Thank you for the report.
Does this mean that the size of the thumbnail file may be 0 bytes in some models? I have more than 1000 models, but I can't find such a thumbnail file.
Copy the thumbnail file [here](https://github.com/SignalFlagZ/sd-webui-civbrowser/blob/ad8762cf98613b3bcb02885164c9053060a98d18/scripts/civsfz_filemanage.py#L282). Using `shutil.copy2`. There's nothing complicated here.
If so, there may be a conflict with other applications. 
SD web ui allows you to replace the preview image.  Or are you using another model manager? Model information may be updated automatically.
In any case, I cannot reproduce the issue, so I will wait for information from others and watch for a while.
