### ISSUE TITLE
CivitaiのSuppoterになっているのにEarly Accessモデルのダウンロードができない

### ISSUE THREAD

**Issue by Taskmak** [SignalFlagZ/sd-civitai-browser#49]
Early Access:がAPIキーを入れていてもダウンロードされません。
.jsonとpng等はダウンロードされますが肝心のモデルデータがダウンロードされません。

**Comment by SignalFlagZ** [comment]
報告ありがとうございます。
> Early Access:がAPIキーを入れていてもダウンロードされません。

課金した事が無いので動作がわかりません。Civitaiでリンクをクリックした後に何かメッセージが表示されその後ダウンロードするのでしょうか？
概略の動作を教えて下さい。それっぽい実装を考えてみます。

**Comment by Taskmak** [comment]
v1.8の頃には普通にEarly Access:はダウンロードされてましたよ
ｖ1.9になってからEarly Access:がダウンロードされなくなってます。
civbrowser上でどのような動きになるかわかりませんが普通にブラウザでＤＬできます。
（civbrowserのDownload hereをクリックするだけでダウンロード出来てるので）

**Comment by SignalFlagZ** [comment]
何か勘違いをしているようですね。通常はダウンロードできないのが正解です。Early Accessというのがなぜ存在しているのか調べることをおすすめします。

**Comment by Taskmak** [comment]
勘違いされてるようですけど・・・？会員になってるから普通にブラウザでDL出来てるんですけど？
だから「civbrowser上でどのような動きになるかわかりませんが」と書いているんです。
以前のバージョンではEarly Access:は普通に落とせたとも書いてます。

**Comment by SignalFlagZ** [comment]
Issuesはチャットや掲示板とは違います。症状を再現するに十分な情報を示してください。あなたが示さない限りあなたの状況を知る手段はありません。再現できないものに対処する方法はありません。
具体的なモデルIDを教えて下さい。また、”会員”というのは何を指しますか？言葉はとても大切です。勝手な単語を作らないでください。Civitaiで使われている英単語を使ってください。そしてあなたのMembershipsのランクを教えて下さい。

**Comment by Taskmak** [comment]
面倒なのでいいますね、前バージョンではなぜEarly Access:が落とせて
現バージョンでは落とせないのででしょうか？
旧バージョンを使用すると普通に落とせますよ？
作者さんが何かをやってるとしか思えませんけど？

**Comment by SignalFlagZ** [comment]
落とせないのが普通です。以前から同じです。Early Accessが何かを調べましょう。具体的なモデルIDの開示がないならクローズします。

**Comment by Taskmak** [comment]
v1.8で落とせている証拠です

https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/161118354/8f1769b2-0e40-4499-b6d6-96c89011d1f3

ｖ1.8で落とせるのに最新版では落とせない意味が分かりません

![WS000113](https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/161118354/67e7a8a2-4428-48e9-90f2-d2555eaf03d5)

最新版の場合はこうなります

https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/161118354/bf9a4531-ee51-4666-8e73-35eaa1548b4f

![WS000114](https://github.com/SignalFlagZ/sd-webui-civbrowser/assets/161118354/9e964b71-c7b8-4427-b7eb-b50f60c4ff3f)

**Comment by SignalFlagZ** [comment]
できない ではなく状態を簡潔に教えて下さい。あなたが何をしていて何を期待しているのかは誰にもわかりません。あなたのメッセージには解析に必要な情報が何も含まれていません。今回のビデオでモデルIDはわかりました。ビデオでは何を言いたいかを理解するのに私の時間を無駄に消費します。文字にしてください。
最初に戻ります。ダウンロードできない時にコンソール画面には何かメッセージが表示されていますか？あなたのサポーターメンバーシップは何ですか？

**Comment by SignalFlagZ** [comment]
タイトルを変更しました。Civitaiアカウントは誰かに作ってもらったのでしょうか？あなたはSupporterになっているのですね？あまり意識していないように見受けられますが最初に書いておいてもらえると助かります。
修正しました 108d22e38a9234ecddb2a5b4fef9586f1af0dc77
