### ISSUE TITLE
特定Loraのパーミッションが異なって表示される

### ISSUE THREAD

**Issue by CircleD5** [SignalFlagZ/sd-civitai-browser#5]
環境：
 AUTOMATIC1111/stable-diffusion-webui Version: 1.6.0
Civitai Browser Version: 1.6.0、1.6.1　ともに確認

現象：
Civitai Browserで読み込んだモデル利用の権限がCivitai上で記載されている権限と異なることがあります。

すみません、不具合が発生するLoraがNSFWのため、少しぼかしますが以下のような例があります。

例：　
Civitai上では以下のように表示されており、画像の商用利用は許可されています。

![スクリーンショット 2023_09_05 13_18_41](https://github.com/SignalFlagZ/sd-civitai-browser/assets/144087288/bded9017-4ed8-4eb0-9da8-7f6301709495)

Civitai Browserで読み込んだ場合、以下のように画像の商用許可が許されていません。

![スクリーンショット 2023_09_05 13_18_412](https://github.com/SignalFlagZ/sd-civitai-browser/assets/144087288/bd4ca358-8491-47f5-8025-deb4c4c37463)

**Comment by CircleD5** [comment]
追記：　
allowCommercialUseに'RentCivit'と記載されている場合に動かないっぽい？
確かにCivitai APIのリファレンスにenum (None, Image, Rent, Sell)とあってRentCivitというのはない。
最近追加されたのだろうか？

**Comment by CircleD5** [comment]
追記

すみません、ちょっと現行のブランチ管理がよくわからんのと、私自身のフロントエンドの知識がゴミなので、プルリク出せないのですが、以下の修正案はいかがでしょうか？

CivitaiのドキュメントにはRentCivitが反映されていないのですが、ソースコードにはすでにパーミッション導出ロジックが記載されているため、それを参考にCivitaiBrowserも変更する。

[Civitai API](https://github.com/civitai/civitai/blob/5116e70412191600e5eda6bcd8b02a3a752b3900/src/components/PermissionIndicator/PermissionIndicator.tsx#L16C1-L16C1)のパーミッション決定の方法と同様のロジックを、[sd-civitai-browserのパーミッションを決定するロジック](https://github.com/SignalFlagZ/sd-civitai-browser/blob/mod/scripts/civitai_api.py#L119)を実装する。

**Comment by SignalFlagZ** [comment]
ありがとうございます。とても助かります。
パーミッション表示が正しいか 公式ドキュメントが存在しないので気にしていました。
ひっそりと更新されているようですね。どこかにリリースノートは出ているんでしょうかね。
該当する属性を持つモデルをいろいろ探さないとデバッグできないのでしばらく時間がかかるかもしれません。

**Comment by SignalFlagZ** [comment]
civitai/civitai@0685f648798a5654ce3b44aab5b59f044ccd2276
変更のコミットを確認

**Comment by SignalFlagZ** [comment]
修正しました c442537295ce35dea0b868d788c555cbdbbeb826
ロジックを変えただけであまり検証していません。この週末くらいまで様子を見て ここはクローズします。

**Comment by CircleD5** [comment]
ありがとうございます！！
先ほどアップデートしたらめちゃくちゃ見やすくなっていて驚きました！

いくつかのRentCivitをダウンロードして使ってみても問題なかったです。
個人的には忘れちゃわないうちにクローズしちゃっても問題ないと思います！
