### ISSUE TITLE
LoraのみNEXT表示が出ない

### ISSUE THREAD

**Issue by taka-0770** [SignalFlagZ/sd-civitai-browser#53]
civitaiが仕様変更したのかどうかはわかりませんが今朝からLoraの項目のみNext表示が出なくなってます

![WS000000](https://github.com/user-attachments/assets/b9b5cb2e-a852-41aa-aab4-89af706f1523)
![WS000001](https://github.com/user-attachments/assets/d417601b-7d6f-49ec-8405-0b26fb1f9efa)

検索種類を１つにした場合のみはNextが表示されます
![WS000004](https://github.com/user-attachments/assets/ed42f4e6-dea7-4da8-8fc6-bdbb5690be44)

Newest_._AllTimeでの表示順も正常に表示されない様です

**Comment by SignalFlagZ** [comment]
報告をありがとうございます。
こちらでも最近一度だけ同様な症状が出ましたが、その後症状は出なくなりました。一時的なCivitai側の問題だったと考えられます。
このIssueはしばらくしてクローズしますが、まだ症状があるようならば報告をお願いします。
Civitaiのデータはブラウザと同じようなプログラムで取得します。同じページの要求でデータに変化がない場合はキャッシュが使われます。Civitai側の何かの動作で Next ページが無いデータを正常受信すると、次回同じページの要求時にキャッシュされたデータが使われ続けます。Civbrowserが再起動しキャッシュがクリアされると新たにデータを受信します。

**Comment by taka-0770** [comment]
Civitai側の問題だとは思いますがソート順がバラバラな様でcivbrowserでもちぐはぐになっている様です。
再起動してみましたがcivbrowserのLoraの部分のみNextが表示されない現象が続いています。

**Comment by SignalFlagZ** [comment]
Sort を Newest 、period を ALLTimeにしていると Next が無効になるようです。Civitaiからのレスポンスに次ページのURL情報が無いためボタンが無効化されます。他の条件ではこの問題は無いようです。
しばらく様子見ですね。

**Comment by SignalFlagZ** [comment]
直ったようなのでクローズします
