### ISSUE TITLE
earlyaccessのダウンロードにBuzzを寄付してダウンロード出来る様にしてほしい

### ISSUE THREAD

**Issue by taka-0770** [SignalFlagZ/sd-civitai-browser#54]
![WS000000](https://github.com/user-attachments/assets/cb1e931c-16ae-45ff-859c-a7a434e67bd7)
画像の様にBuzzを寄付してからでないとダウンロード出来なくなっています。
これをcivbrowser上でも可能にして頂けると助かります。

**Comment by SignalFlagZ** [comment]
リクエストありがとう
クリエイターに対して良い機能ですね。しかしAPIが存在しない機能は作ることができません。モデルのリンクをブラウザで開くしかありません。

**Comment by hargn111** [comment]
Early Access status is available via json["items"][modelIndex]["modelVersions"][versionIndex]["availability"] with the value of "EarlyAccess" (vs "Public") - no time frame is available yet it appears. But at least can have the card/textbox show EA.

**Comment by SignalFlagZ** [comment]
> But at least can have the card/textbox show EA.

Although it is not directly related to this issue, I have made some corrections.
bf2adb862d04fe603680bcf73c7d8909acb21d03
