### ISSUE TITLE
Forgeでも使える様にして欲しい

### ISSUE THREAD

**Issue by taka-0770** [SignalFlagZ/sd-civitai-browser#55]
今まではForgeでも使えていましたがForgeがGradio 4を使用の為
civbrowserが利用できなくなってしまいました。Forgeでも使える様に
Gradio 4対応して頂けたら助かります。

**Comment by SignalFlagZ** [comment]
要望ありがとうございます。
Forgeブランチで対応を始めました。今のところエラーが出ないようにしただけですが一通りは動くようになっているでしょう。また、Forge側にブラウザが重くなる不具合が発生しているようで 現在使い心地がとても悪いです。
Gradioは更新が早いです。逆に言うとバグや仕様変更が多いです。バグなのか仕様なのかを調べるのにとても時間がかかります。後方互換性が無い機能もあります。まだ本気でGradio4に対応する気にはなりません。こなれていないバージョンをForgeが使い続ける事にならないといいなぁ。

**Comment by SignalFlagZ** [comment]
version: [f2.0.1v1.10.1-previous-281-g7fcfb930](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/7fcfb93090a25cdf067d8a8c5d19c42229c23e52) にアップデートしたらCivBrowserに限らず多くのExtensionsが動かなくなっています。動くのもあるし何が違うのだろう？

**Comment by SignalFlagZ** [comment]
Solved in #56
