### ISSUE TITLE
Allow renaming of a model before downloading

### ISSUE THREAD

**Issue by Terroosh** [SignalFlagZ/sd-civitai-browser#57]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to rename a model before it downloads

**Describe alternatives you've considered**
You can rename manually after download but that is time consuming

**Additional context**
Many models have nonsensical names or share common names. I'd like to be able to rename the model prior to downloading.  Civitai browser+ had this feature by renaming the model in the "Model Filename" field but unfortunately that extension appears to have stopped receiving updates. The easiest way would probably be something similar.

**Comment by SignalFlagZ** [comment]
Thanks for the new suggestion.
If you rename it, you won't be able to tell if it's already been downloaded. Is that ok?

I don't want to record renames in a database or record file hash values. That's a redundant and time-consuming process that the web UI already does. 
However, if we use extra networks, it would be useful to be able to specify a unique model, for example with a hash value. Isn't this an appropriate request for the web UI?

**Comment by Terroosh** [comment]
It's fine if I can't tell if it's downloaded. Thank you for the addition. Comparing the file hash to the civitai hash probably is time consuming though it does have some merits. Models get taken down by civitai/authors all the time and then you'll have people repost the model with a different name. Though I'm fine with how it currently is.
