### ISSUE TITLE
最新版のForgeで所持済とアップデートされた物の色表示が変更できない

### ISSUE THREAD

**Issue by taka-0770** [SignalFlagZ/sd-civitai-browser#60]
settingにある
Frame color for cards you already have
Frame color for cards with updates
この２つの色を変更しても反映されなくなってます。

最新版は
Version: f2.0.1v1.10.1-previous-528-ge55cde9b
Commit hash: e55cde9b3335bdfcdbac6845e0c9509fca2b89e7
です

**Comment by SignalFlagZ** [comment]
報告ありがとうございます。
修正しました。
