### ISSUE TITLE
Delay in loading process

### ISSUE THREAD

**Issue by taka-0770** [SignalFlagZ/sd-civitai-browser#9]
There are many times when I try to load a model or LORA page and it just takes time and it doesn't display at all.

**Comment by SignalFlagZ** [comment]
Thanks for reporting the glitch.
The gradio component is taking a lot of time to load and update. The more extensions there are, the more load time it takes. If you press a button before the component update is complete, that event will not trigger. Clicking on the same model as before will not trigger the event. After clicking on a different model, click on the desired model.
These are noticeable in the SD web UI. SD.Next seems to handle them faster.

**Comment by taka-0770** [comment]
I'm using it locally, and there's a discrepancy between what is displayed in the Civitai browser and the URL being shown in the Civitai browser
